searchengine=https://duckduckgo.com/?q=$1
spitefulness=9.7

; comments are preceeded by a semicolon...
; each section concerns an individual enemy
[larry]
fullname=Larry Doe
type=kindergarten bully
website=http://www.geocities.com/capeCanaveral/11451

[davaeorn]
fullname=davaeorn
type=evil wizard
outputdir=C:\Users\anuju\local_repos\activities\outputs
